project_id = "bcqfogudctmltxvwluyb"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true
port = 54325

[auth]
enabled = true
port = 54326

[edge_functions]
enabled = true
port = 54327

[functions.transcribe-audio]
verify_jwt = false

[functions.transcribe-streaming]
verify_jwt = false

[functions.ask-gemini]
verify_jwt = false

[functions.speak-gtts]
verify_jwt = false

[functions.import-storyweaver]
verify_jwt = false

[functions.get-content]
verify_jwt = false

[functions.import-sfx]
verify_jwt = false

[functions.import-rhyme]
verify_jwt = false

[functions.import-audiobook]
verify_jwt = false

[functions.import-storynory]
verify_jwt = false

[functions.bulk-import]
verify_jwt = false

[functions.repair-module]
verify_jwt = false

[functions.noun-extract]
verify_jwt = false